# Generated by Django 4.2.9 on 2024-07-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='eva1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eva 1'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='eva2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eva 2'),
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='eva3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Eva 3'),
        ),
    ]
