# Generated by Django 4.2.9 on 2024-07-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_calificaciones_calificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificaciones',
            name='fecha',
        ),
    ]
